[package]
name = "au2far"
version = "0.1.0"
authors = ["Yuki Kodama <endflow.net@gmail.com>"]
edition = "2018"

[dependencies]
base64 = "0.11.0"
image = "0.22.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
